apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name }}
  annotations:
    'edgefarm.io/cluster': ${{ values.clusterName }}
    'edgefarm.io/release-image': ${{ values.image }}
  links:
    - url: https://www.ci4rail.com
      title: Ci4Rail Website
      icon: backstage
spec:
  type: Plan
  owner: ${{ values.owner }}
  lifecycle: production
  system: ${{ values.system }}
