apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.deviceName }}
  annotations:
    'edgefarm.io/cluster': ${{ values.clusterName }}
spec:
  type: Device
  owner: ${{ values.owner }}
  lifecycle: production
  system: ${{ values.system }}
