apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: edgefarm-network-add
  title: New Network
  description: Add a new network to the edgefarm
  tags:
    - edgefarm
    - network
    - recommended
    - streaming
    - nats
  links:
    - title: Documentation
      url: https://edgefarm.io/docs/networks
  annotations:
    edgefarm/visibility: public
spec:
  type: service
  parameters:
    - title: Specify some general parameters here
      required:
        - system
        - name
        - namespace
      properties:
        system:
          title: Select your system
          description:
            Here you can select one of your existing systems. If you don't have
            any, you need to create one first.
          type: string
          ui:field: EntityPicker
          ui:options:
            catalogFilter:
              - kind: system
            defaultKind: System
        name:
          title: Name of the network
          title: Name of the network
          type: string
          maxLength: 253
          pattern: ^[a-z0-9][a-z0-9-]*$
          ui:autofocus: true
          ui:options:
            rows: 5
        namespace:
          title: Namespace of the network
        namespace:
          title: Namespace of the network
          type: string
          maxLength: 253
          pattern: ^[a-z0-9][a-z0-9-]*$
          ui:options:
            rows: 5
    - title: Specify the subnetworks
      required:
        - subnetworks
      properties:
        subnetworks:
          type: array
          title: Subnetworks
          description: Here you can add one or more subnetworks to the network.
          minItems: 1
          ui:options:
            orderable: false
          items:
            type: object
            required:
              - name
              - fileStorage
              - inMemoryStorage
            properties:
              name:
                type: string
                title: Name of subnetwork
                description:
                  The name of the subnetwork. This name will be used as a prefix for
                  the subnetwork's resources.
                ui:autofocus: true
              fileStorage:
                type: string
                default: 1Gi
                pattern: ^[1-9][0-9]*(Ki|Mi|Gi|Ti|Pi|Ei)*$
                title: Specify how much file storage the network should have. (e.g. 1Gi)
              inMemoryStorage:
                type: string
                default: 100Mi
                pattern: ^[1-9][0-9]*(Ki|Mi|Gi|Ti|Pi|Ei)*$
                title: Specify how much in-memory storage the network should have. (e.g. 1Gi)
    - title: Specify the NATS streams
      required:
        - streams
      properties:
        streams:
          title: Streams
          type: array
          minItems: 1
          ui:options:
            orderable: false
          items:
            type: object
            required:
              - name
              - config
            ui:options:
              orderable: false
            properties:
              name:
                type: string
                title: Name of the Stream
                ui:autofocus: true
              config:
                type: object
                required:
                  - subjects
                  - discard
                  - retention
                  - storage
                  - maxConsumers
                  - maxMsgSize
                  - maxMsgs
                  - maxMsgsPerSubject
                  - maxBytes
                properties:
                  subjects:
                    type: array
                    minItems: 1
                    ui:options:
                      orderable: false
                    items:
                      type: string
                      title: Subject
                  discard:
                    type: string
                    title: Discard
                    default: Old
                    enum:
                      - Old
                      - New
                      - All
                    enumNames:
                      - Old
                      - New
                      - All
                  retention:
                    type: string
                    title: Retention
                    default: Limits
                    enum:
                      - Limits
                      - Interest
                      - WorkQueue
                      - File
                      - Memory
                    enumNames:
                      - Limits
                      - Interest
                      - WorkQueue
                      - File
                      - Memory
                  storage:
                    type: string
                    title: Storage
                    default: File
                    enum:
                      - File
                      - Memory
                    enumNames:
                      - File
                      - Memory
                  maxConsumers:
                    default: -1
                    type: integer
                    minimun: -1
                    ui:widget: updown
                  maxMsgSize:
                    default: -1
                    type: integer
                    minimun: -1
                    ui:widget: updown
                  maxMsgs:
                    default: -1
                    type: integer
                    minimun: -1
                    ui:widget: updown
                  maxMsgsPerSubject:
                    default: -1
                    type: integer
                    minimun: -1
                    ui:widget: updown
                  maxBytes:
                    default: 102400
                    type: integer
                    minimun: 1
                    ui:widget: updown
    - title: Specify the users
      required:
        - users
      properties:
        users:
          type: array
          title: Users
          description: Here you can add one or more users to the network.
          minItems: 1
          ui:options:
            orderable: false
          items:
            type: object
            required: []
            properties:
              name:
                type: string
                title: Unique name of the user
                description:
                  The name of the user. This name will be used as a prefix for the
                  user's resources.
                ui:autofocus: true
              limits:
                type: object
                properties:
                  payload:
                    type: integer
                    title: Payload
                    description: The maximum payload size in bytes.
                    default: 1000
                  data:
                    type: integer
                    title: Data
                    description: The maximum data size in bytes.
                    default: -1
                    minimium: -1
                  subscriptions:
                    type: integer
                    title: Subscriptions
                    description: The maximum number of subscriptions.
                    default: -1
                    minimium: -1
              permissions:
                type: object
                properties:
                  pub:
                    type: object
                    properties:
                      allow:
                        type: array
                        title: Allow
                        description: The list of subjects that are allowed to publish to the network.
                        items:
                          type: string
                      deny:
                        type: array
                        title: Deny
                        description:
                          The list of subjects that are not allowed to publish to the
                          network.
                        items:
                          type: string
                  sub:
                    type: object
                    properties:
                      allow:
                        type: array
                        title: Allow
                        description: The list of subjects that are allowed to subscribe to the network.
                        items:
                          type: string
                      deny:
                        type: array
                        title: Deny
                        description:
                          The list of subjects that are not allowed to subscribe to the
                          network.
                        items:
                          type: string
  steps:
    - id: system-fetch
      name: Fetch system entity
      action: catalog:fetch
      input:
        entityRef: ${{ parameters.system }}
    - id: fetch-base
      name: Fetch Base
      action: fetch:template
      input:
        url: ./content
        targetPath: networks/${{ parameters.name }}
        targetPath: networks/${{ parameters.name }}
        values:
          clusterName: ${{ steps['system-fetch'].output.entity.metadata.annotations['edgefarm.io/cluster'] }}
          name: ${{ parameters.name }}
          namespace: ${{ parameters.namespace }}
          subnetworks: ${{ parameters.subnetworks }}
          streams: ${{ parameters.streams }}
          users: ${{ parameters.users }}
          namespace: ${{ parameters.namespace }}
          subnetworks: ${{ parameters.subnetworks }}
          streams: ${{ parameters.streams }}
          users: ${{ parameters.users }}
          owner: ${{ user.entity.metadata.namespace }}/${{ user.entity.metadata.name }}
          system: ${{ parameters.system }}
    - id: list-workspace
      name: List Workspace
      action: debug:log
      input:
        listWorkspace: true
    - id: read-file
      name: Read File
      action: ci4rail:fs:read
      input:
        path: ./networks/${{ parameters.name }}/manifests/network.yaml
    - id: log-message
      name: Log Message
      action: debug:log
      input:
        message: ${{ steps['read-file'].output.content }}
    - id: read-file2
      name: Read File
      action: ci4rail:fs:read
      input:
        path: ./networks/${{ parameters.name }}/catalog-info.yaml
    - id: log-message2
      name: Output catalog-info.yaml
      action: debug:log
      input:
        message: ${{ steps['read-file2'].output.content }}
  output:
    links:
      - title: Open pull request
        description: foobar
        url: ${{ steps['pull-request'].output.remoteUrl }}
