apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name | dump }}
  annotations:
    backstage.io/kubernetes-label-selector: 'app=edge-network-${{ values.name | lower | replace(" ", "-") }}'
    argocd/app-name: ${{ values.name }}
  links:
    - url: https://www.ci4rail.com
      title: Ci4Rail Website
      icon: backstage
spec:
  type: EdgeNetwork
  lifecycle: experimental
