apiVersion: network.edgefarm.io/v1alpha1
kind: EdgeNetwork
metadata:
  name: edge-network-${{ values.name | lower | replace(" ", "-") }}
  labels:
    app: edge-network-${{ values.name | lower | replace(" ", "-") }}
spec:
  nodeSelector: 
    project: ${{ values.name | lower | replace(" ", "-") }}
  network: test-network-def-${{ values.name | lower | replace(" ", "-") }}
  limits:
    fileStorage: 10G
    inMemoryStorage: 1G
