apiVersion: apps/v1
kind: Deployment
metadata:
  name: 'edge-network-nginx-${{ values.name | lower | replace(" ", "-") }}'
  labels:
    app: 'edge-network-${{ values.name | lower | replace(" ", "-") }}'
spec:
  replicas: ${{ values.replica }}
  selector:
    matchLabels:
      app: 'edge-network-${{ values.name | lower | replace(" ", "-") }}'
  template:
    metadata:
      labels:
        app: 'edge-network-${{ values.name | lower | replace(" ", "-") }}'
    spec:
      containers:
        - name: 'edge-network-nginx-${{ values.name | lower | replace(" ", "-") }}'
          image: nginx:latest
          imagePullPolicy: Always