apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: edgefarm-node-add
  title: New Node
  description: Add a new node to the edgefarm
  tags:
    - edgefarm
    - node
    - recommended
    - kubernetes
  links:
    - title: Documentation
      url: https://edgefarm.io/docs/nodes
spec:
  type: service
  parameters:
    - title: Fill in some steps
      required:
        - name
        - system
      properties:
        system:
          title: Select your system
          description: Here you can select one of your existing systems. If you don't have any, you need to create one first.
          type: string
          ui:field: EntityPicker
          ui:options:
            catalogFilter:
              - kind: system
            defaultKind: System
        name:
          title: Name of the node
          type: string
          description: Unique name of the kubernetes node
          maxLength: 253 # DNS subdomain name rules: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#dns-subdomain-names
          pattern: "^[a-z0-9][a-z0-9-]*$"
          ui:autofocus: true
          ui:options:
            rows: 5

  steps:
    - id: system-fetch
      name: Fetch system entity
      action: catalog:fetch
      input:
        entityRef: ${{ parameters.system }}
    - id: fetch-base
      name: Fetch Base
      action: fetch:template
      input:
        url: ./content
        targetPath: nodes/${{ parameters.name }}
        values:
          clusterName: ${{ steps['system-fetch'].output.entity.metadata.annotations['edgefarm.io/cluster'] }}
          nodeName: ${{ parameters.name }}
          owner: ${{ user.entity.metadata.namespace }}/${{ user.entity.metadata.name }}
          system: ${{ parameters.system }}
    - id: list-workspace
      name: List Workspace
      action: debug:log
      input:
        listWorkspace: true
    - id: read-file
      name: Read File
      action: ci4rail:fs:read
      input:
        path: ./nodes/${{ parameters.name }}/catalog-info.yaml
    - id: log-message
      name: Log Message
      action: debug:log
      input:
        message: ${{ steps['read-file'].output.content }}

    - id: pull-request
      name: Create Pull Request
      action: publish:github:pull-request
      input:
        token: ${{ secrets.USER_OAUTH_TOKEN }}
        repoUrl: ${{ steps['system-fetch'].output.entity.metadata.annotations['edgefarm.io/repo'] }}
        branchName: add-node-${{ parameters.name }}-definition
        title: Add node ${{ parameters.name }} definition
        description: Adds a new node with name ${{ parameters.name }}
        gitAuthorName: ${{ user.entity.metadata.name }}
        gitAuthorEmail: ${{ user.entity.spec.profile.email }}

  output:
    links:
      - title: Open pull request
        url: ${{ steps['pull-request'].output.remoteUrl }}
