apiVersion: apps/v1
kind: Deployment
metadata:
  name: edgenetwork-${{ values.name }}
  labels:
    app: edgenetwork-${{ values.name }}
spec:
  replicas: ${{ values.replica | dump }}
  selector:
    matchLabels:
      app: edgenetwork-${{ values.name }}
  template:
    metadata:
      labels:
        app: edgenetwork-${{ values.name }}
    spec:
      containers:
        - name: edgenetwork-${{ values.name }}
          image: nginx:latest
          imagePullPolicy: Always